# .github/workflows/test.yaml
name: testerino
on:
  push:
    branches: [ "main" ]
    
    
jobs:
  testing_using_selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
     #Setup Python   
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.1.0

        
      - name: Install the necessary packages
        run: pip install selenium pytest
        
      - name: Run the PytTest script
        run: pytest -s --tb=short ./"Tests för Kjell o Company"/test_Kjell.py
