# .github/workflows/test.yaml
name: testerino
on:
  push:
    branches: [ "main" ]
    
    
jobs:
  
  run_tests_selenium:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install the necessary packages
      run: pip install selenium pytest

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1.1.0
      
    - name: Setup Firefox
      uses: browser-actions/setup-firefox@v1
      
    - name: Setup Firefox
      run: sudo apt update && sudo apt install microsoft-edge-stable


    - name: Run Chrome tests
      run: pytest -s --tb=short --browser=chrome ./"Tests för Kjell o Company"/test_Kjell.py
      
    - name: Run Firefox tests
      run: pytest -s --tb=short --browser=firefox ./"Tests för Kjell o Company"/test_Kjell.py
